---
title: "High prediction accuracy for asthma at 3 years based on nasal and gut microbiome colonization patterns and human milk components (Figure 5)"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Setup 

```{r, warning=FALSE, message=FALSE}
R.version.string
library(phyloseq); packageVersion('phyloseq')
library(ggplot2); packageVersion('ggplot2')
library(cowplot); packageVersion('cowplot')
library(vegan); packageVersion('vegan')
library(tidyr); packageVersion('tidyr')
library(reshape2); packageVersion('reshape2')
library(dplyr); packageVersion('dplyr')  
library(lmPerm); packageVersion('lmPerm')
library(UpSetR); packageVersion('UpSetR')
library(ComplexHeatmap); packageVersion('ComplexHeatmap')
library(circlize); packageVersion('circlize')
library(gbm); library('MASS')
library(pROC)


source("Preprocessing/Functions.R")
```

```{r}

```

### Microbiota Trajectory data subsets used
```{r}
Nasal_3M1Y_pa_filt <- readRDS("Data_subsets/Main_Nasal_Trajectory_Subset.rds") # Prevalence dataset

Gut_3M1Y_pa_filt <- readRDS("Data_subsets/Main_Gut_Trajectory_Subset.rds") # Prevalence dataset
```


