---
title: "Figure S2. Microbiota richness at individual time-points across nasal and gut microbial niches."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Similar to scripts for main Figure 2C-2F, but just select individual time-points**
Also see Fig_2.Rmd for exact p-values in 'Wilcoxon_Res_Fig2D_2F_and_SuppTraj_ColPat_Richness.csv'

## Setup

```{r, warning=FALSE, message=FALSE}
R.version.string
library(phyloseq); packageVersion('phyloseq')
library(ggplot2); packageVersion('ggplot2')
library(dplyr); packageVersion('dplyr')  
library(tidyr); packageVersion('tidyr')
library(reshape2); packageVersion('reshape2')
library(ggsignif); packageVersion('ggsignif')
library(here)

source(paste0(here::here(), "/Functions.R"))

theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5,face = "bold"), strip.text.x = element_text(size = 11), strip.background = element_rect(colour="white", fill="white"), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), text = element_text(size=12), axis.text = element_text(color="black", size=12), legend.key.size = unit(0.5,"cm")))

Trj_cols <- c("#f2aeb0", "#f08a0c")
```

**Data subset used**
```{r} 
# Derived Trajectory variables for the Trajectory subsets
Traj_data_ls <- readRDS(paste0(path, "Data/Data_subsets/ALL_Trajectory_Derived_Data.rds")) 
```

### Microbiota 3-month 1-year paired data subsets 

```{r}
# Main metadata variables to test
Main_vars_Traj <- c("BF_status_3m_sampling", "asthma_3y") 

### List of variables to be used for these analysis
Single_tp <- c("Observed_N3m", "Observed_G3m", "Observed_N1y", "Observed_G1y")
```

```{r} 
NG_Traj_sdf <- merge( subset(Traj_data_ls$Trajectories_Nasal_to181_Gut_at182, select = Single_tp),
                      subset(Traj_data_ls$Metadata, select=Main_vars_Traj), 
                      by="row.names" )
```

### Individual timepoints data for plotting

```{r}
NG_Traj_sdf_m <- melt(NG_Traj_sdf, measure.vars = Single_tp) %>%
                    mutate(Dataset = factor(ifelse(grepl("_G", variable), "Gut", "Nasal"), levels = c("Nasal", "Gut")),
                           var_type = ifelse(grepl("Shannon_N1y3m|Shannon_G1y3m", variable), "Diversity Trajectory",
                                      ifelse(grepl("Observed_N1y3m|Observed_G1y3m", variable), "Richness Trajectory",
                                      ifelse(grepl("Shannon", variable), "Diversity", 
                                      ifelse(grepl("Observed", variable), "Richness", "Colonization"))))
                           )

## split data for plots
NG_Traj_sdf_m_Tp <- subset(NG_Traj_sdf_m, variable %in% Single_tp)
NG_Traj_sdf_m_Tp$Visit <- ifelse(grepl("3", NG_Traj_sdf_m_Tp$variable), "3-Month", "1-Year")
NG_Traj_sdf_m_Tp$Visit <- factor(NG_Traj_sdf_m_Tp$Visit, levels = c("3-Month", "1-Year"))
```

**Supplementary, Nasal and Gut Richness at individual time-points**
```{r, warning=FALSE}
# warnings about missing / non-finite values are ok - this is because of the NA valuse in the data (not all participants have both nasal and gut trajectory data)

#table(NG_Traj_sdf_m_Tp$Dataset, NG_Traj_sdf_m_Tp$Visit) ## these factors combined is the same as the "variable" column for individual timepoints

# Breastfeeding
NG_Traj_sdf_m_Tp_BF <- subset(NG_Traj_sdf_m_Tp, BF_status_3m_sampling != "Partial")

Fig_S2AB_BF <- ggplot(NG_Traj_sdf_m_Tp_BF, aes(x=BF_status_3m_sampling, y=value, group=BF_status_3m_sampling)) + 
  facet_wrap(~Visit*Dataset, scales = "free_y") + 
  geom_jitter(aes(color=Dataset),shape=16, size=1.5, alpha=0.25, position = position_jitter(width = 0.2)) +
  geom_violin(trim = FALSE, alpha=0) + 
  stat_summary(fun=median, geom="point", shape=23, size=2, fill="black")  + 
  scale_y_continuous(expand=c(0,0)) + 
  theme(axis.text = element_text(size=9), legend.position = "none", strip.text.x = element_text(face="bold")) +
  labs(y="Microbiota Richness", x="Breastfeeding Exclusivity at 3 Months") + 
  scale_color_manual(values = Trj_cols) +
  geom_signif(color="black", comparisons = list(c("Exclusive", "No BM")), test = "wilcox.test", step_increase = 0.2, vjust = 1.5, map_signif_level = c("**"=0.001, "*"=0.05,"~"=0.1," "=2), size=0, textsize = 7) 
Fig_S2AB_BF

## Asthma 3 years
NG_Traj_sdf_m_Tp_Ast <- subset(NG_Traj_sdf_m_Tp, asthma_3y != "Possible")

Fig_S2AB_Asthma <- ggplot(NG_Traj_sdf_m_Tp_Ast, aes(x=asthma_3y, y=value, group=asthma_3y)) + 
  facet_wrap(~Visit*Dataset, scales = "free_y") + 
  geom_jitter(aes(color=Dataset),shape=16, size=1.5, alpha=0.25, position = position_jitter(width = 0.2)) +
  geom_violin(trim = FALSE, alpha=0) + 
  stat_summary(fun=median, geom="point", shape=23, size=2, fill="black")  + 
  scale_y_continuous(expand=c(0,0)) + 
  theme(axis.text = element_text(size=9), legend.position = "none", strip.text.x = element_text(face="bold")) +
  labs(y="Microbiota Richness", x="Asthma at 3 Years") + scale_color_manual(values = Trj_cols) +
  geom_signif(color="black", comparisons = list(c("No", "Yes")), test = "wilcox.test", step_increase = 0.2, vjust = 1.5, map_signif_level = c("**"=0.001, "*"=0.05,"~"=0.1," "=2), size=0, textsize = 7) 
Fig_S2AB_Asthma
```

```{r, warning=FALSE, include=FALSE} 
tiff(file = paste0(path, "Figures/Fig_S2A_S2B_BF3m_Richness.tiff"), width = 1440, height = 1440, units = "px", res = 300) 
Fig_S2AB_BF
dev.off()

tiff(file = paste0(path, "Figures/Fig_S2A_S2B_Asthma3y_Richness.tiff"), width = 1440, height = 1440, units = "px", res = 300)
Fig_S2AB_Asthma
dev.off()
```


